Repository AlonsoOropeza/PugSeal, pull requests merged in 2020-10, with the labels that each got.

#9 Upload: Added compatibility for MacOS
  .DS_Store
  Pug-Backend/.DS_Store
  Pug-Backend/cannis/.DS_Store
  Pug-Backend/cannis/cannis/__pycache__/__init__.cpython-38.pyc
  Pug-Backend/cannis/cannis/__pycache__/settings.cpython-38.pyc
  Pug-Backend/cannis/cannis/__pycache__/urls.cpython-38.pyc
  Pug-Backend/cannis/cannis/__pycache__/wsgi.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/__init__.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/admin.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/forms.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/models.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/serializer.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/views.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/migrations/__pycache__/0001_initial.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/migrations/__pycache__/0002_auto_20201002_2118.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/migrations/__pycache__/__init__.cpython-38.pyc
  Pug-Backend/djangocannis/.DS_Store
Labels: setup

#18 agregar datatables
  Pug-Backend/cannis/cannis/__pycache__/urls.cpython-38.pyc
  Pug-Backend/cannis/db.sqlite3
  Pug-Backend/cannis/pugsealapp/__pycache__/views.cpython-38.pyc
  Pug-Frontend/angular.json
  Pug-Frontend/package-lock.json
  Pug-Frontend/package.json
  Pug-Frontend/src/app/admin/categorias/categorias.component.html
  Pug-Frontend/src/app/admin/categorias/categorias.component.ts
  Pug-Frontend/src/app/admin/datatable/datatable.component.css
  Pug-Frontend/src/app/admin/datatable/datatable.component.html
  Pug-Frontend/src/app/admin/datatable/datatable.component.ts
  Pug-Frontend/src/app/app.module.ts
  Pug-Frontend/src/app/forms/categoria-form/categoria-form.component.html
  Pug-Frontend/src/app/layouts/admin-layout/admin-layout.routing.ts
  Pug-Frontend/src/app/models/models.model.ts
Labels: feature, refactor, setup

#22 Feature/crear area
  Pug-Backend/cannis/cannis/__pycache__/__init__.cpython-38.pyc
  Pug-Backend/cannis/cannis/__pycache__/settings.cpython-38.pyc
  Pug-Backend/cannis/cannis/__pycache__/urls.cpython-38.pyc
  Pug-Backend/cannis/cannis/__pycache__/wsgi.cpython-38.pyc
  Pug-Backend/cannis/cannis/urls.py
  Pug-Backend/cannis/db.sqlite3
  Pug-Backend/cannis/pugsealapp/__pycache__/__init__.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/admin.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/forms.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/models.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/serializer.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/views.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/migrations/__pycache__/0001_initial.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/migrations/__pycache__/0002_auto_20201002_2118.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/migrations/__pycache__/__init__.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/views.py
  Pug-Backend/djangocannis/Lib/site-packages/django/contrib/admin/views/__pycache__/decorators.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/django/contrib/admindocs/__pycache__/__init__.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/django/contrib/admindocs/__pycache__/utils.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/django/contrib/admindocs/__pycache__/views.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/django/db/backends/sqlite3/__pycache__/__init__.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/django/db/backends/sqlite3/__pycache__/base.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/django/db/backends/sqlite3/__pycache__/client.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/django/db/backends/sqlite3/__pycache__/creation.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/django/db/backends/sqlite3/__pycache__/features.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/django/db/backends/sqlite3/__pycache__/introspection.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/django/db/backends/sqlite3/__pycache__/operations.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/django/db/backends/sqlite3/__pycache__/schema.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/rest_framework/__pycache__/authentication.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/rest_framework/__pycache__/decorators.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/rest_framework/__pycache__/filters.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/rest_framework/__pycache__/generics.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/rest_framework/__pycache__/metadata.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/rest_framework/__pycache__/mixins.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/rest_framework/__pycache__/negotiation.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/rest_framework/__pycache__/permissions.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/rest_framework/__pycache__/response.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/rest_framework/__pycache__/views.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/rest_framework/__pycache__/viewsets.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/rest_framework/schemas/__pycache__/__init__.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/rest_framework/schemas/__pycache__/coreapi.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/rest_framework/schemas/__pycache__/generators.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/rest_framework/schemas/__pycache__/inspectors.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/rest_framework/schemas/__pycache__/openapi.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/rest_framework/schemas/__pycache__/utils.cpython-38.pyc
  Pug-Backend/djangocannis/Lib/site-packages/rest_framework/utils/__pycache__/mediatypes.cpython-38.pyc
  Pug-Frontend/src/app/admin/areas/areas.component.css
  Pug-Frontend/src/app/admin/areas/areas.component.html
  Pug-Frontend/src/app/admin/areas/areas.component.spec.ts
  Pug-Frontend/src/app/admin/areas/areas.component.ts
  Pug-Frontend/src/app/app.module.ts
  Pug-Frontend/src/app/forms/area-form/area-form.component.css
  Pug-Frontend/src/app/forms/area-form/area-form.component.html
  Pug-Frontend/src/app/forms/area-form/area-form.component.spec.ts
  Pug-Frontend/src/app/forms/area-form/area-form.component.ts
  Pug-Frontend/src/app/layouts/admin-layout/admin-layout.routing.ts
  Pug-Frontend/src/app/services/areas.service.ts
  Pug-Frontend/src/app/services/notifications.service.ts
  Pug-Frontend/src/app/sidebar/sidebar.component.ts
Labels: feature

#23 CRUD database
  Pug-Backend/cannis/cannis/__pycache__/__init__.cpython-38.pyc
  Pug-Backend/cannis/cannis/__pycache__/settings.cpython-38.pyc
  Pug-Backend/cannis/cannis/__pycache__/urls.cpython-38.pyc
  Pug-Backend/cannis/cannis/__pycache__/wsgi.cpython-38.pyc
  Pug-Backend/cannis/cannis/urls.py
  Pug-Backend/cannis/db.sqlite3
  Pug-Backend/cannis/package.json
  Pug-Backend/cannis/pugsealapp/__pycache__/__init__.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/admin.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/apps.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/forms.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/models.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/serializer.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/views.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/migrations/0001_initial.py
  Pug-Backend/cannis/pugsealapp/migrations/0002_auto_20201002_2118.py
  Pug-Backend/cannis/pugsealapp/migrations/__pycache__/0001_initial.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/migrations/__pycache__/0002_auto_20201002_1856.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/migrations/__pycache__/0002_auto_20201002_2118.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/migrations/__pycache__/__init__.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/models.py
  Pug-Backend/cannis/pugsealapp/serializer.py
  Pug-Backend/cannis/pugsealapp/tests/__init__.py
  Pug-Backend/cannis/pugsealapp/tests/__pycache__/__init__.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/tests/__pycache__/test_forms.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/tests/__pycache__/test_models.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/tests/__pycache__/test_urls.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/tests/__pycache__/test_views.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/tests/test_forms.py
  Pug-Backend/cannis/pugsealapp/tests/test_models.py
  Pug-Backend/cannis/pugsealapp/tests/test_urls.py
  Pug-Backend/cannis/pugsealapp/tests/test_views.py
Labels: feature, fix, refactor, setup
