Repository AlonsoOropeza/PugSeal, pull requests merged in 2020-11, with the labels that each got.

#30 Upload: created model for bitacora medicion
  Pug-Backend/cannis/pugsealapp/models.py
Labels: feature

#32 Feature/registrar mant prev
  Pug-Backend/cannis/cannis/urls.py
  Pug-Backend/cannis/pugsealapp/models.py
  Pug-Backend/djangocannis/pyvenv.cfg
  Pug-Frontend/src/app/admin/mantenimiento-preventivo/mantenimiento-preventivo.component.css
  Pug-Frontend/src/app/admin/mantenimiento-preventivo/mantenimiento-preventivo.component.html
  Pug-Frontend/src/app/admin/mantenimiento-preventivo/mantenimiento-preventivo.component.ts
  Pug-Frontend/src/app/models/models.model.ts
  Pug-Frontend/src/app/services/mantenimiento.service.ts
  Pug-Frontend/src/app/services/mantenimiento_preventivo.service.ts
Labels: feature, invalid

#33 Fix conflicts
  Pug-Backend/cannis/cannis/urls.py
  Pug-Backend/cannis/db.sqlite3
  Pug-Backend/cannis/pugsealapp/models.py
Labels: fix, refactor, setup

#34 Feature/crear mant prev
  Pug-Backend/cannis/pugsealapp/models.py
  Pug-Backend/cannis/pugsealapp/serializer.py
  Pug-Backend/cannis/pugsealapp/views.py
  Pug-Backend/requirements.txt
  Pug-Frontend/src/app/admin/mantenimiento-preventivo/mantenimiento-preventivo.component.html
  Pug-Frontend/src/app/admin/mantenimiento-preventivo/mantenimiento-preventivo.component.ts
  Pug-Frontend/src/app/admin/proveedores/proveedores.component.html
  Pug-Frontend/src/app/admin/proveedores/proveedores.component.ts
  Pug-Frontend/src/app/forms/mantenimiento-preventivo-form/mantenimiento-preventivo-form.component.html
  Pug-Frontend/src/app/forms/mantenimiento-preventivo-form/mantenimiento-preventivo-form.component.ts
  Pug-Frontend/src/app/models/models.model.ts
  Pug-Frontend/src/app/services/empleados.service.ts
  Pug-Frontend/src/app/services/login.service.ts
  Pug-Frontend/src/app/services/mantenimiento_preventivo.service.ts
  Pug-Frontend/src/app/services/notifications.service.ts
Labels: feature, refactor, wontfix

#35 Refactor/query auditores
  Pug-Backend/cannis/cannis/urls.py
  Pug-Backend/cannis/pugsealapp/views.py
  Pug-Frontend/src/app/admin/mantenimiento-preventivo/mantenimiento-preventivo.component.html
  Pug-Frontend/src/app/forms/mantenimiento-preventivo-form/mantenimiento-preventivo-form.component.html
  Pug-Frontend/src/app/forms/mantenimiento-preventivo-form/mantenimiento-preventivo-form.component.ts
  Pug-Frontend/src/app/services/areas.service.ts
  Pug-Frontend/src/app/services/categorias.service.ts
  Pug-Frontend/src/app/services/empleados.service.ts
Labels: fix, refactor

#37 Bitacora + Estilos
  Pug-Backend/djangocannis/Lib/site-packages/rest_framework/static/rest_framework/css/bootstrap.min.css
  Pug-Backend/djangocannis/Lib/site-packages/rest_framework/static/rest_framework/css/prettify.css
  Pug-Backend/djangocannis/Lib/site-packages/rest_framework/static/rest_framework/docs/css/base.css
  Pug-Frontend/src/app/admin/areas/areas.component.css
  Pug-Frontend/src/app/admin/areas/areas.component.html
  Pug-Frontend/src/app/admin/bitacora-mediciones/bitacora-mediciones.component.css
  Pug-Frontend/src/app/admin/bitacora-mediciones/bitacora-mediciones.component.html
  Pug-Frontend/src/app/admin/bitacora-mediciones/bitacora-mediciones.component.ts
  Pug-Frontend/src/app/admin/categorias/categorias.component.css
  Pug-Frontend/src/app/admin/categorias/categorias.component.html
  Pug-Frontend/src/app/admin/mantenimiento-preventivo/mantenimiento-preventivo.component.css
  Pug-Frontend/src/app/admin/mantenimiento-preventivo/mantenimiento-preventivo.component.html
  Pug-Frontend/src/app/admin/proveedores/proveedores.component.css
  Pug-Frontend/src/app/admin/proveedores/proveedores.component.html
  Pug-Frontend/src/app/forms/area-form/area-form.component.css
  Pug-Frontend/src/app/forms/bitacora-mediciones-form/bitacora-mediciones-form.component.css
  Pug-Frontend/src/app/forms/categoria-form/categoria-form.component.css
  Pug-Frontend/src/app/forms/mantenimiento-preventivo-form/mantenimiento-preventivo-form.component.css
  Pug-Frontend/src/app/forms/proveedor-form/proveedor-form.component.css
  Pug-Frontend/src/app/sidebar/sidebar.component.ts
  Pug-Frontend/src/assets/css/jquery.dataTables.css
  Pug-Frontend/src/styles.css
Labels: feature

#38 Deploy produccion
  Pug-Backend/cannis/cannis/settings.py
  script_bd.txt
Labels: refactor

#49 Feature/mantenimiento preventivo
  Pug-Backend/cannis/pugsealapp/__pycache__/__init__.cpython-39.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/admin.cpython-39.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/models.cpython-39.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/serializer.cpython-39.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/views.cpython-39.pyc
  Pug-Backend/cannis/pugsealapp/migrations/__pycache__/0001_initial.cpython-39.pyc
  Pug-Frontend/src/app/admin/mantenimiento-preventivo/mantenimiento-preventivo.component.html
  Pug-Frontend/src/app/admin/mantenimiento-preventivo/mantenimiento-preventivo.component.ts
  Pug-Frontend/src/app/admin/presupuesto/presupuesto.component.html
  Pug-Frontend/src/app/admin/presupuesto/presupuesto.component.ts
  Pug-Frontend/src/app/login/login.component.ts
Labels: bug, invalid

#60 Fix/release
  Pug-Backend/cannis/pugsealapp/__pycache__/forms.cpython-38.pyc
Labels: fix
