Repository AlonsoOropeza/PugSeal, pull requests merged in 2020-12, with the labels that each got.

#55 Feature/asignar semanas
  Pug-Backend/cannis/cannis/__pycache__/__init__.cpython-38.pyc
  Pug-Backend/cannis/cannis/__pycache__/settings.cpython-38.pyc
  Pug-Backend/cannis/cannis/__pycache__/urls.cpython-38.pyc
  Pug-Backend/cannis/cannis/__pycache__/wsgi.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/__init__.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/__init__.cpython-39.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/admin.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/admin.cpython-39.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/forms.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/models.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/models.cpython-39.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/serializer.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/serializer.cpython-39.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/views.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/views.cpython-39.pyc
  Pug-Backend/cannis/pugsealapp/migrations/0001_initial.py
  Pug-Backend/cannis/pugsealapp/migrations/0002_auto_20201127_2040.py
  Pug-Backend/cannis/pugsealapp/migrations/__pycache__/0001_initial.cpython-39.pyc
  Pug-Backend/cannis/pugsealapp/models.py
  Pug-Frontend/src/app/admin/actividades/actividades.component.html
  Pug-Frontend/src/app/admin/actividades/actividades.component.ts
  Pug-Frontend/src/app/admin/mantenimiento-preventivo/mantenimiento-preventivo.component.html
  Pug-Frontend/src/app/admin/mantenimiento-preventivo/mantenimiento-preventivo.component.ts
  Pug-Frontend/src/app/admin/presupuesto/presupuesto.component.html
  Pug-Frontend/src/app/admin/presupuesto/presupuesto.component.ts
  Pug-Frontend/src/app/app.module.ts
  Pug-Frontend/src/app/forms/actividades-form/actividades-form.component.css
  Pug-Frontend/src/app/forms/actividades-form/actividades-form.component.html
  Pug-Frontend/src/app/forms/actividades-form/actividades-form.component.spec.ts
  Pug-Frontend/src/app/forms/actividades-form/actividades-form.component.ts
  Pug-Frontend/src/app/forms/mantenimiento-preventivo-form/mantenimiento-preventivo-form.component.html
  Pug-Frontend/src/app/forms/mantenimiento-preventivo-form/mantenimiento-preventivo-form.component.ts
  Pug-Frontend/src/app/login/login.component.html
  Pug-Frontend/src/app/login/login.component.ts
  Pug-Frontend/src/app/models/models.model.ts
  Pug-Frontend/src/app/sidebar/sidebar.component.ts
Labels: feature

#62 remover comentarios y funciones muertas
  Pug-Frontend/src/app/admin/bitacora-mediciones/bitacora-mediciones.component.ts
  Pug-Frontend/src/app/admin/calendario/calendario.component.ts
  Pug-Frontend/src/app/admin/incidencias/incidencias.component.ts
  Pug-Frontend/src/app/admin/mantenimiento-correctivo/mantenimiento-correctivo.component.ts
  Pug-Frontend/src/app/admin/mantenimiento-preventivo/mantenimiento-preventivo.component.ts
  Pug-Frontend/src/app/forms/mantenimiento-correctivo-form/mantenimiento-correctivo-form.component.ts
  Pug-Frontend/src/app/layouts/admin-layout/admin-layout.component.ts
  Pug-Frontend/src/app/login/login.component.ts
  Pug-Frontend/src/app/services/bitacora-mediciones.service.ts
  Pug-Frontend/src/app/services/login.service.ts
  Pug-Frontend/src/app/shared/navbar/navbar.component.ts
Labels: fix, refactor

#63 Release v1.2
  Pug-Backend/cannis/cannis/__pycache__/__init__.cpython-38.pyc
  Pug-Backend/cannis/cannis/__pycache__/settings.cpython-38.pyc
  Pug-Backend/cannis/cannis/__pycache__/urls.cpython-38.pyc
  Pug-Backend/cannis/cannis/__pycache__/wsgi.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/__init__.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/__init__.cpython-39.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/admin.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/admin.cpython-39.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/forms.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/models.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/models.cpython-39.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/serializer.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/serializer.cpython-39.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/views.cpython-38.pyc
  Pug-Backend/cannis/pugsealapp/__pycache__/views.cpython-39.pyc
  Pug-Backend/cannis/pugsealapp/migrations/0001_initial.py
  Pug-Backend/cannis/pugsealapp/migrations/0002_auto_20201127_2040.py
  Pug-Backend/cannis/pugsealapp/migrations/__pycache__/0001_initial.cpython-39.pyc
  Pug-Backend/cannis/pugsealapp/models.py
  Pug-Frontend/src/app/admin/actividades/actividades.component.html
  Pug-Frontend/src/app/admin/actividades/actividades.component.ts
  Pug-Frontend/src/app/admin/bitacora-mediciones/bitacora-mediciones.component.ts
  Pug-Frontend/src/app/admin/calendario/calendario.component.ts
  Pug-Frontend/src/app/admin/incidencias/incidencias.component.ts
  Pug-Frontend/src/app/admin/mantenimiento-correctivo/mantenimiento-correctivo.component.ts
  Pug-Frontend/src/app/admin/mantenimiento-preventivo/mantenimiento-preventivo.component.html
  Pug-Frontend/src/app/admin/mantenimiento-preventivo/mantenimiento-preventivo.component.ts
  Pug-Frontend/src/app/admin/presupuesto/presupuesto.component.html
  Pug-Frontend/src/app/admin/presupuesto/presupuesto.component.ts
  Pug-Frontend/src/app/app.module.ts
  Pug-Frontend/src/app/forms/actividades-form/actividades-form.component.css
  Pug-Frontend/src/app/forms/actividades-form/actividades-form.component.html
  Pug-Frontend/src/app/forms/actividades-form/actividades-form.component.spec.ts
  Pug-Frontend/src/app/forms/actividades-form/actividades-form.component.ts
  Pug-Frontend/src/app/forms/mantenimiento-correctivo-form/mantenimiento-correctivo-form.component.ts
  Pug-Frontend/src/app/forms/mantenimiento-preventivo-form/mantenimiento-preventivo-form.component.html
  Pug-Frontend/src/app/forms/mantenimiento-preventivo-form/mantenimiento-preventivo-form.component.ts
  Pug-Frontend/src/app/layouts/admin-layout/admin-layout.component.ts
  Pug-Frontend/src/app/login/login.component.html
  Pug-Frontend/src/app/login/login.component.ts
  Pug-Frontend/src/app/models/models.model.ts
  Pug-Frontend/src/app/services/bitacora-mediciones.service.ts
  Pug-Frontend/src/app/services/login.service.ts
  Pug-Frontend/src/app/shared/navbar/navbar.component.ts
  Pug-Frontend/src/app/sidebar/sidebar.component.ts
Labels: Release

#65 Fix Bootsrap
  Pug-Frontend/documentation/tutorial-lbd-angular2.html
  Pug-Frontend/src/app/login/login.component.css
  Pug-Frontend/src/app/login/login.component.html
  Pug-Frontend/src/index.html
Labels: fix

#66 Hot fix production
  Pug-Frontend/documentation/tutorial-lbd-angular2.html
  Pug-Frontend/src/app/login/login.component.css
  Pug-Frontend/src/app/login/login.component.html
  Pug-Frontend/src/index.html
Labels: bug, fix

#67 fix asignacion meses
  Pug-Frontend/src/app/admin/mantenimiento-preventivo/mantenimiento-preventivo.component.ts
Labels: fix, refactor
